package orchestrator

import (
	"context"
	"errors"
	"fmt"
	"os"
	"regexp"
	"strings"
	"unicode"

	"github.com/bryann2k/maestro/internal/agentcore"
	"github.com/bryann2k/maestro/internal/session"
	"github.com/bryann2k/maestro/internal/spec"
)

// envVarRe matches ALL_CAPS token candidates in spec text.
var envVarRe = regexp.MustCompile(`\b[A-Z][A-Z0-9_]{2,}\b`)

// envVarDenylist skips technical acronyms that are not env vars.
var envVarDenylist = map[string]bool{
	"API": true, "HTTP": true, "ID": true, "URL": true, "JSON": true,
	"YAML": true, "TOML": true, "SQL": true, "ADR": true, "CORS": true,
	"RLS": true, "MCP": true, "LSP": true, "TUI": true, "IDE": true,
	"CLI": true, "RAG": true, "OWASP": true, "AES": true, "HITL": true,
	"F1": true, "F2": true, "F3": true, "F4": true, "F5": true,
	"F6": true, "F7": true, "F8": true, "F9": true, "USD": true,
	"SSE": true, "GPT": true, "NPM": true, "CI": true, "GO": true,
	"README": true, "TODO": true, "TBD": true, "V1": true, "V2": true,
	"ENV": true, "FS": true, "SSH": true, "DNS": true, "CPU": true,
}

// HITLItems returns the deterministic human actions required for the
// current phase: missing env vars, pending diff review, runbook steps.
// Items are derived from spec + git — never generated by the LLM.
func (o *Orchestrator) HITLItems(ctx context.Context) ([]agentcore.HITLItem, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	var items []agentcore.HITLItem
	if o.sess.Draft != nil {
		for _, question := range o.sess.Draft.Questions {
			status := "pending"
			if question.Status == "resolved" || strings.TrimSpace(question.Answer) != "" {
				status = "done"
			}
			items = append(items, agentcore.HITLItem{
				ID: "spec:" + question.ID, Item: question.Prompt, Status: status, Blocking: question.Blocking,
			})
		}
	}
	if o.spec != nil {
		items = append(items, o.missingEnvItems()...)
		items = append(items, o.runbookItems()...)
	}
	if o.sess.Phase == session.PhaseBuild || o.sess.Phase == session.PhaseReview {
		st, err := o.git.Status(ctx)
		if err == nil && st.Dirty {
			items = append(items, agentcore.HITLItem{ID: "diff", Item: "Review the git diff", Status: "pending"})
		}
	}
	if len(items) == 0 {
		return nil, nil
	}
	o.applyPersistedHITLStatus(items)
	return items, nil
}

// missingEnvItems reports only variables the spec explicitly requires an
// operator to provision. A bare ALL_CAPS mention is not enough: runtime
// inputs with a documented fallback (for example GREETING_NAME) must never
// manufacture an .env gate.
func (o *Orchestrator) missingEnvItems() []agentcore.HITLItem {
	envData, _ := os.ReadFile(o.envFilePath())
	envSet := map[string]bool{}
	for _, line := range strings.Split(string(envData), "\n") {
		line = strings.TrimSpace(line)
		line = strings.TrimSpace(strings.TrimPrefix(line, "export "))
		if key, value, ok := strings.Cut(line, "="); ok && key != "" && strings.TrimSpace(value) != "" {
			envSet[strings.TrimSpace(key)] = true
		}
	}
	seen := map[string]bool{}
	var items []agentcore.HITLItem
	contract := hitlContractText(o.spec)
	for _, tok := range envVarRe.FindAllString(contract, -1) {
		runtimeValue, runtimeSet := os.LookupEnv(tok)
		if envVarDenylist[tok] || seen[tok] || envSet[tok] || (runtimeSet && runtimeValue != "") {
			continue
		}
		seen[tok] = true
		if !requiresEnvProvisioning(contract, tok) {
			continue
		}
		label := fmt.Sprintf("Provide required environment variable %s", tok)
		if envFileProvisioning(contract, tok) {
			label = fmt.Sprintf("Fill .env with %s", tok)
		}
		items = append(items, agentcore.HITLItem{
			ID:       "env:" + tok,
			Item:     label,
			Status:   "pending",
			Blocking: true,
		})
	}
	return items
}

func envFileProvisioning(contract, token string) bool {
	for _, context := range tokenContexts(contract, token) {
		if strings.Contains(normalizeEnvContext(context), ".env") {
			return true
		}
	}
	return false
}

// hitlContractText keeps the detector on human-authored contract language
// without scanning YAML IDs or verifier commands as if they were variables.
func hitlContractText(sp *spec.Spec) string {
	if sp == nil {
		return ""
	}
	var parts []string
	parts = append(parts, sp.Title, sp.Body)
	parts = append(parts, sp.Success...)
	parts = append(parts, sp.Decisions...)
	for _, requirement := range sp.Requirements {
		parts = append(parts, requirement.Statement)
		for _, scenario := range requirement.Scenarios {
			parts = append(parts, scenario.Given...)
			parts = append(parts, scenario.When)
			parts = append(parts, scenario.Then...)
		}
	}
	for _, batch := range sp.Batches {
		parts = append(parts, batch.Name)
		parts = append(parts, batch.Tasks...)
		parts = append(parts, batch.Accept...)
	}
	return strings.Join(parts, "\n")
}

// requiresEnvProvisioning is intentionally conservative. It needs explicit
// provisioning language (required/must + set/configure, or a direct .env
// instruction) and lets any token-specific optional/default contract win.
// That makes the action a real operator gate rather than an ALL_CAPS guess.
func requiresEnvProvisioning(contract, token string) bool {
	contexts := tokenContexts(contract, token)
	for _, context := range contexts {
		if optionalEnvContext(context) {
			return false
		}
	}
	for _, context := range contexts {
		if explicitEnvProvisioning(context, token) {
			return true
		}
	}
	return false
}

func tokenContexts(text, token string) []string {
	lines := strings.Split(text, "\n")
	var contexts []string
	for i, line := range lines {
		if !strings.Contains(line, token) {
			continue
		}
		start, end := max(i-1, 0), min(i+2, len(lines))
		contexts = append(contexts, strings.Join(lines[start:end], " "))
	}
	return contexts
}

func normalizeEnvContext(value string) string {
	value = strings.ToLower(value)
	return strings.NewReplacer("’", "'", "`", "", "**", "").Replace(value)
}

func optionalEnvContext(context string) bool {
	lower := normalizeEnvContext(context)
	if containsAny(lower,
		"optional", "optionnel", "optionnelle", "facultatif", "facultative",
		"fallback", "fall back", "default value", "defaults to", "valeur par défaut",
		"repli", "may be omitted", "peut être omis", "peut être omise", "not required",
		"n'est pas requis", "n'est pas requise", "non obligatoire",
	) {
		return true
	}
	// Specifications often describe fallback behavior without using the word
	// "fallback": "use world when absent or empty" is still unambiguously
	// non-provisioning.
	hasMissingCase := containsAny(lower, " absent", "absente", "empty", " vide", "unset", "not set", "non défin")
	hasFallbackBehavior := containsAny(lower, "use ", "utiliser ", "uses ", "prend ", "vaut ", "world", "otherwise", "sinon")
	return hasMissingCase && hasFallbackBehavior
}

func explicitEnvProvisioning(context, token string) bool {
	lower := normalizeEnvContext(context)
	if containsAny(lower, "must not", "do not", "don't", "never", "ne pas", "aucun secret", "sans secret") {
		return false
	}
	words := envWords(lower)
	mandatory := containsAny(words,
		" required ", " mandatory ", " must ", " requis ", " requise ", " obligatoire ", " doit ", " doivent ",
	)
	provision := containsAny(words,
		" set ", " provide ", " provided ", " configure ", " configured ", " define ", " defined ",
		" populate ", " populated ", " contain ", " contains ", " fill ", " filled ", " add ", " added ",
		" renseigner ", " renseigné ", " renseignée ", " configurer ", " configuré ", " configurée ",
		" définir ", " défini ", " définie ", " fournir ", " fourni ", " fournie ", " remplir ", " rempli ",
		" remplie ", " contenir ", " contient ", " ajouter ", " ajouté ", " ajoutée ",
	)
	if (strings.Contains(lower, ".env") && provision) || (mandatory && provision) {
		return true
	}
	quoted := regexp.QuoteMeta(strings.ToLower(token))
	requiredAfter := regexp.MustCompile(quoted + `.{0,32}(?:is )?(?:required|mandatory|requis|requise|obligatoire)`)
	requiredBefore := regexp.MustCompile(`(?:required|mandatory|requis|requise|obligatoire).{0,48}` + quoted)
	return requiredAfter.MatchString(lower) || requiredBefore.MatchString(lower)
}

func envWords(value string) string {
	value = strings.Map(func(r rune) rune {
		if unicode.IsLetter(r) {
			return unicode.ToLower(r)
		}
		return ' '
	}, value)
	return " " + strings.Join(strings.Fields(value), " ") + " "
}

func containsAny(value string, needles ...string) bool {
	for _, needle := range needles {
		if strings.Contains(value, needle) {
			return true
		}
	}
	return false
}

const humanActionPermissionType = "human_action"

func (o *Orchestrator) hitlScope() string {
	if o.spec != nil && o.spec.ID != "" {
		return o.spec.ID
	}
	if o.sess.Draft != nil && o.sess.Draft.ID != "" {
		return o.sess.Draft.ID
	}
	return o.sess.SpecID
}

func (o *Orchestrator) applyPersistedHITLStatus(items []agentcore.HITLItem) {
	scope := o.hitlScope()
	for _, permission := range o.sess.PermQueue {
		if permission.Type != humanActionPermissionType || permission.Scope != scope || permission.Status != "done" {
			continue
		}
		for i := range items {
			// Structured questions are resolved only by /answer. Treating a
			// cosmetic checkbox as an answer would make the rail disagree with
			// the actual /accept readiness gate.
			if strings.HasPrefix(items[i].ID, "spec:") {
				continue
			}
			if items[i].ID == permission.ID && items[i].Status != "done" {
				items[i].Status = "done"
			}
		}
	}
}

// SetHITLStatus persists a TUI checkbox decision in the current spec/draft
// scope. This keeps acknowledgements coherent across refreshes and restarts
// without leaking them into the next feature cycle.
func (o *Orchestrator) SetHITLStatus(ctx context.Context, id string, done bool) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	id = strings.TrimSpace(id)
	if id == "" || id == "hitl" {
		return errors.New("hitl action requires a concrete ID")
	}
	if strings.HasPrefix(id, "spec:") {
		return errors.New("spec questions must be resolved with /answer")
	}
	scope := o.hitlScope()
	if scope == "" {
		return errors.New("hitl action has no active spec or draft")
	}
	status := "pending"
	if done {
		status = "done"
	}
	for i := range o.sess.PermQueue {
		permission := &o.sess.PermQueue[i]
		if permission.Type == humanActionPermissionType && permission.ID == id && permission.Scope == scope {
			permission.Status = status
			return o.save()
		}
	}
	o.sess.PermQueue = append(o.sess.PermQueue, session.Permission{
		ID: id, Type: humanActionPermissionType, Scope: scope, Status: status,
	})
	return o.save()
}

func (o *Orchestrator) resetHITLStatus(id string) error {
	scope := o.hitlScope()
	for i := range o.sess.PermQueue {
		permission := &o.sess.PermQueue[i]
		if permission.Type == humanActionPermissionType && permission.ID == id && permission.Scope == scope {
			permission.Status = "pending"
			return o.save()
		}
	}
	return nil
}

func (o *Orchestrator) pendingBlockingHITLItems(ctx context.Context) ([]agentcore.HITLItem, error) {
	items, err := o.HITLItems(ctx)
	if err != nil {
		return nil, err
	}
	pending := items[:0]
	for _, item := range items {
		if item.Blocking && item.Status != "done" {
			pending = append(pending, item)
		}
	}
	return pending, nil
}

// runbookItems extracts "Run: ..." steps from the spec body.
func (o *Orchestrator) runbookItems() []agentcore.HITLItem {
	var items []agentcore.HITLItem
	for _, line := range strings.Split(o.spec.Body, "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "Run:") || strings.HasPrefix(line, "- Run ") {
			items = append(items, agentcore.HITLItem{
				ID:     "run:" + shortID(line),
				Item:   strings.TrimPrefix(strings.TrimPrefix(line, "Run:"), "- Run "),
				Status: "pending",
			})
		}
	}
	return items
}

func (o *Orchestrator) envFilePath() string {
	dir := o.baseDir
	if o.sess.Worktree != "" {
		dir = o.sess.Worktree
	}
	return dir + string(os.PathSeparator) + ".env"
}

func shortID(s string) string {
	if len(s) > 24 {
		return s[:24]
	}
	return s
}
