package context

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestImportRules(t *testing.T) {
	dir := t.TempDir()
	write := func(rel, content string) {
		t.Helper()
		path := filepath.Join(dir, rel)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatalf("MkdirAll: %v", err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatalf("WriteFile: %v", err)
		}
	}
	write(".cursor/rules/go.mdc", "---\ndescription: Go style\nglobs: **/*.go\n---\nUse error wrapping with %w.\n")
	write(".clinerules", "Keep functions small.\n")
	write("AGENTS.md", "# Project\n\nRun go test before commit.\n")
	write(".github/copilot-instructions.md", "---\napplyTo: \"**/*.go\"\n---\nFollow Effective Go.\n")

	rules, err := ImportRules(dir)
	if err != nil {
		t.Fatalf("ImportRules: %v", err)
	}
	kinds := map[string]bool{}
	origins := map[string]bool{}
	for _, r := range rules {
		kinds[r.Kind] = true
		origins[r.Origin] = true
	}
	if !kinds[KindMDC] || !kinds[KindCliRules] || !kinds[KindAgentsMD] || !kinds[KindApplyTo] {
		t.Errorf("kinds = %v", kinds)
	}
	// The MDC file carries its globs.
	for _, r := range rules {
		if r.Kind == KindMDC {
			if len(r.ApplyTo) != 1 || r.ApplyTo[0] != "**/*.go" {
				t.Errorf("mdc applyTo = %v", r.ApplyTo)
			}
			if !strings.Contains(r.Content, "error wrapping") {
				t.Errorf("mdc content = %q", r.Content)
			}
		}
	}
	if len(origins) < 4 {
		t.Errorf("origins = %v", origins)
	}
}

func TestImportEmpty(t *testing.T) {
	rules, err := ImportRules(t.TempDir())
	if err != nil {
		t.Fatalf("ImportRules: %v", err)
	}
	if len(rules) != 0 {
		t.Errorf("rules = %+v", rules)
	}
}

func TestExportFormats(t *testing.T) {
	rules := []ImportedRule{
		{Origin: "a.mdc", Kind: KindMDC, ApplyTo: []string{"**/*.go"}, Content: "rule one"},
		{Origin: "AGENTS.md", Kind: KindAgentsMD, Content: "rule two"},
	}
	agents, err := ExportRules(rules, "AGENTS.md")
	if err != nil || !strings.Contains(agents, "rule one") || !strings.Contains(agents, "rule two") || !strings.Contains(agents, "Generated by Maestro") {
		t.Errorf("agents export = %q, %v", agents, err)
	}
	mdc, err := ExportRules(rules, "mdc")
	if err != nil || !strings.Contains(mdc, "globs: **/*.go") {
		t.Errorf("mdc export = %q, %v", mdc, err)
	}
	clines, err := ExportRules(rules, "clinerules")
	if err != nil || !strings.Contains(clines, "rule one") {
		t.Errorf("clinerules export = %q, %v", clines, err)
	}
	if _, err := ExportRules(rules, "bogus"); err == nil {
		t.Error("unknown format should fail")
	}
}

func TestExportEmpty(t *testing.T) {
	if _, err := ExportRules(nil, "AGENTS.md"); err == nil {
		t.Error("export without rules should fail")
	}
}

func TestMergeSourcesTracksOrigins(t *testing.T) {
	rules := []ImportedRule{
		{Origin: "/x/a.mdc", Kind: KindMDC, Content: "rule one"},
	}
	merged := MergeSources(rules)
	if !strings.Contains(merged, "/x/a.mdc") || !strings.Contains(merged, "rule one") {
		t.Errorf("merged = %q", merged)
	}
}
