// Package context implements rules import/export (F8, §11.1): reads Cursor
// MDC, Cline .clinerules, Codex AGENTS.md, and Copilot applyTo files in
// place, and generates any target format from a single merged source.
package context

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Rule kinds.
const (
	KindMDC      = "mdc"
	KindCliRules = "clinerules"
	KindAgentsMD = "agentsmd"
	KindApplyTo  = "applyto"
)

// ImportedRule is one rule read from a rules file.
type ImportedRule struct {
	Origin  string   `json:"origin"` // absolute file path
	Kind    string   `json:"kind"`
	ApplyTo []string `json:"apply_to,omitempty"` // scope (glob)
	Content string   `json:"content"`
}

// ImportRules reads every supported rules file in the project.
func ImportRules(projectDir string) ([]ImportedRule, error) {
	var rules []ImportedRule

	// Cursor: .cursor/rules/*.mdc
	mdcFiles, _ := filepath.Glob(filepath.Join(projectDir, ".cursor", "rules", "*.mdc"))
	for _, f := range mdcFiles {
		rules = append(rules, parseMDC(f)...)
	}

	// Cline: .clinerules (dir of files or single file)
	cr := filepath.Join(projectDir, ".clinerules")
	if fi, err := os.Stat(cr); err == nil {
		if fi.IsDir() {
			entries, _ := os.ReadDir(cr)
			for _, e := range entries {
				if !e.IsDir() && strings.HasSuffix(e.Name(), ".md") {
					if data, err := os.ReadFile(filepath.Join(cr, e.Name())); err == nil {
						rules = append(rules, ImportedRule{
							Origin: filepath.Join(cr, e.Name()), Kind: KindCliRules,
							Content: strings.TrimSpace(string(data)),
						})
					}
				}
			}
		} else if data, err := os.ReadFile(cr); err == nil {
			rules = append(rules, ImportedRule{Origin: cr, Kind: KindCliRules, Content: strings.TrimSpace(string(data))})
		}
	}

	// Codex/agents: AGENTS.md at root (and CLAUDE.md).
	for _, name := range []string{"AGENTS.md", "CLAUDE.md"} {
		f := filepath.Join(projectDir, name)
		if data, err := os.ReadFile(f); err == nil {
			rules = append(rules, ImportedRule{Origin: f, Kind: KindAgentsMD, Content: strings.TrimSpace(string(data))})
		}
	}

	// Copilot: .github/copilot-instructions.md with applyTo frontmatter.
	ci := filepath.Join(projectDir, ".github", "copilot-instructions.md")
	if data, err := os.ReadFile(ci); err == nil {
		rules = append(rules, parseApplyTo(ci, data)...)
	}

	return rules, nil
}

// parseMDC reads one .mdc file: optional YAML frontmatter (description,
// globs) + body.
func parseMDC(path string) []ImportedRule {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	content := string(data)
	applyTo := []string{}
	if fmStart := strings.Index(content, "---"); fmStart == 0 {
		if fmEnd := strings.Index(content[3:], "---"); fmEnd >= 0 {
			fm := content[3 : 3+fmEnd]
			for _, line := range strings.Split(fm, "\n") {
				line = strings.TrimSpace(line)
				if strings.HasPrefix(line, "globs:") || strings.HasPrefix(line, "applyTo:") {
					rest := strings.TrimSpace(strings.TrimPrefix(strings.TrimPrefix(line, "globs:"), "applyTo:"))
					for _, g := range strings.Split(rest, ",") {
						applyTo = append(applyTo, strings.Trim(strings.TrimSpace(g), `"'`))
					}
				}
			}
			content = content[3+fmEnd+3:]
		}
	}
	return []ImportedRule{{
		Origin: path, Kind: KindMDC, ApplyTo: applyTo,
		Content: strings.TrimSpace(content),
	}}
}

// parseApplyTo reads a Copilot instructions file with frontmatter.
func parseApplyTo(path string, data []byte) []ImportedRule {
	content := string(data)
	applyTo := []string{}
	if fmStart := strings.Index(content, "---"); fmStart == 0 {
		if fmEnd := strings.Index(content[3:], "---"); fmEnd >= 0 {
			fm := content[3 : 3+fmEnd]
			for _, line := range strings.Split(fm, "\n") {
				line = strings.TrimSpace(line)
				if strings.HasPrefix(line, "applyTo:") {
					rest := strings.TrimSpace(strings.TrimPrefix(line, "applyTo:"))
					for _, g := range strings.Split(rest, ",") {
						applyTo = append(applyTo, strings.Trim(strings.TrimSpace(g), `"'`))
					}
				}
			}
			content = content[3+fmEnd+3:]
		}
	}
	return []ImportedRule{{
		Origin: path, Kind: KindApplyTo, ApplyTo: applyTo,
		Content: strings.TrimSpace(content),
	}}
}

// ExportRules renders the merged rules in a target format (F8 mono-source:
// one source of truth, every tool's format generated from it).
func ExportRules(rules []ImportedRule, format string) (string, error) {
	if len(rules) == 0 {
		return "", errors.New("no rules to export")
	}
	var b strings.Builder
	switch format {
	case "agentsmd", "AGENTS.md", "claude", "CLAUDE.md":
		b.WriteString("# Project Rules\n\n")
		b.WriteString("> Generated by Maestro from project rules (F8). Edit the source rules, not this file.\n\n")
		for _, r := range rules {
			fmt.Fprintf(&b, "## %s (%s)\n\n%s\n\n", filepath.Base(r.Origin), r.Kind, r.Content)
		}
	case "mdc":
		for _, r := range rules {
			fmt.Fprintf(&b, "---\ndescription: imported from %s\nglobs: %s\n---\n\n%s\n\n", filepath.Base(r.Origin), strings.Join(r.ApplyTo, ", "), r.Content)
		}
	case "clinerules":
		for _, r := range rules {
			b.WriteString(r.Content + "\n\n")
		}
	default:
		return "", fmt.Errorf("unknown export format %q", format)
	}
	return b.String(), nil
}

// MergeSources returns the merged rule content with origins tracked.
func MergeSources(rules []ImportedRule) string {
	var b strings.Builder
	for _, r := range rules {
		fmt.Fprintf(&b, "<!-- from %s (%s) -->\n%s\n\n", r.Origin, r.Kind, r.Content)
	}
	return strings.TrimSpace(b.String())
}

// SortedKeys is a small helper for deterministic iteration.
func SortedKeys(m map[string][]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
